package snse;

import java.awt.event.*;




/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Accueil.java
 *
 * Created on Apr 28, 2012, 11:49:13 PM
 */
/**
 *
 * @author user
 */
public class Accueil extends javax.swing.JFrame {

    public static int image_index = 1;
    String background_Image = "accueil.jpg";
    javax.swing.Timer t;

    /** Creates new form Accueil */
    public Accueil() {
        initComponents();
        this.setLocation(265, 51);
        t = new javax.swing.Timer(60000, new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                Evenement.check_event_auto();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Système de notification et synchronisation des évènements");
        setMinimumSize(new java.awt.Dimension(691, 616));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/gmail_priority_inbox copy.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 320, 250, 230);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/calendar copy.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 320, 230, 230);

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 0, 48));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SNSE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 90, 150, 110);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ne ratez plus rien avec SNSE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 220, 350, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Votre agenda électronique et consultant de votre messagerie");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 270, 440, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/precedent.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(620, 550, 30, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/suivant.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(650, 550, 30, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/accueil.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 686, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
    email e = new email();
    e.setVisible(true);
}//GEN-LAST:event_jLabel2MouseClicked

private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
    jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    // TODO add your handling code here:
}//GEN-LAST:event_jLabel2MouseEntered

private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
    jLabel2.setBorder(null);
// TODO add your handling code here:
}//GEN-LAST:event_jLabel2MouseExited

private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
    jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
}//GEN-LAST:event_jLabel1MouseEntered

private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
    jLabel1.setBorder(null);// TODO add your handling code here:
}//GEN-LAST:event_jLabel1MouseExited

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

//    javax.swing.JOptionPane.showMessageDialog(null," test_pfc@yahoo.fr        Pass1word\ntest.pfc.zf@gmail.com  Pass1word\nPour tester sinon tu peux tester avec ton gmail");
    // TODO add your handling code here:
    image_index = Enregitrer.Dser_background_image();
    switch (image_index) {
        case 1:
            background_Image = "accueil.jpg";
            break;
        case 2:
            background_Image = "accueil2.jpg";
            break;
        case 3:
            background_Image = "accueil3.jhhpg";
            break;
        case 4:
            background_Image = "accueil4.jpg";
            break;
        case 5:
            background_Image = "accueil5.jpg";
            break;
        case 6:
            background_Image = "accueil6.jpg";
            break;
        case 7:
            background_Image = "accueil7.jpg";
            break;
        case 8:
            background_Image = "accueil8.jpg";
            break;
        default:
            background_Image = "accueil.jpg";
    }
    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/" + background_Image)));
    Evenement.remplire_arry();
    Evenement.check_event_auto();
    t.start();

}//GEN-LAST:event_formWindowOpened

private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
    image_index++;
    if (image_index % 9 == 0) {
        image_index = 1;
    }
    switch (image_index) {
        case 1:
            background_Image = "accueil.jpg";
            break;
        case 2:
            background_Image = "accueil2.jpg";
            break;
        case 3:
            background_Image = "accueil3.jpg";
            break;
        case 4:
            background_Image = "accueil4.jpg";
            break;
        case 5:
            background_Image = "accueil5.jpg";
            break;
        case 6:
            background_Image = "accueil6.jpg";
            break;
        case 7:
            background_Image = "accueil7.jpg";
            break;
        case 8:
            background_Image = "accueil8.jpg";
            break;
        default:
            background_Image = "accueil.jpg";
    }
    Enregitrer.Ser_background_image(image_index);
    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/" + background_Image)));
}//GEN-LAST:event_jLabel8MouseClicked

private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
    image_index--;
    if (image_index == 0) {
        image_index = 8;
    }
    switch (image_index) {
        case 1:
            background_Image = "accueil.jpg";
            break;
        case 2:
            background_Image = "accueil2.jpg";
            break;
        case 3:
            background_Image = "accueil3.jpg";
            break;
        case 4:
            background_Image = "accueil4.jpg";
            break;
        case 5:
            background_Image = "accueil5.jpg";
            break;
        case 6:
            background_Image = "accueil6.jpg";
            break;
        case 7:
            background_Image = "accueil7.jpg";
            break;
        case 8:
            background_Image = "accueil8.jpg";
            break;
        default:
            background_Image = "accueil.jpg";
    }
    Enregitrer.Ser_background_image(image_index);
    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/" + background_Image)));
    // TODO add your handling code here:
}//GEN-LAST:event_jLabel7MouseClicked

private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

    Event ev = new Event();
    ev.setVisible(true);
    // TODO add your handling code here:
}//GEN-LAST:event_jLabel1MouseClicked

private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

}//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
