/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Consulter.java
 *
 * Created on Jun 3, 2012, 7:12:48 PM
 */
package snse;

import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Consulter extends javax.swing.JFrame {

    public ArrayList<Evenement_obj> global_array = new ArrayList<Evenement_obj>();
    public int operation = 0;

    /** Creates new form Consulter */
    public Consulter() {
        initComponents();
        this.setLocation(265, 51);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        Supp = new javax.swing.JButton();
        Modi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(691, 616));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Mes Évènements ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 120, 140, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 220, 480, 270);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tous", "Un jour", "Semaine prochaine", " " }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(280, 110, 103, 37);

        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(280, 160, 103, 29);

        Supp.setText("Supprimer");
        Supp.setMinimumSize(new java.awt.Dimension(691, 616));
        Supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuppActionPerformed(evt);
            }
        });
        getContentPane().add(Supp);
        Supp.setBounds(460, 150, 90, 30);

        Modi.setText("Modifier");
        Modi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModiActionPerformed(evt);
            }
        });
        getContentPane().add(Modi);
        Modi.setBounds(460, 160, 90, 32);

        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(460, 113, 90, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/new_message.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 690, 605);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    int image_index = 0;
    image_index = Enregitrer.Dser_background_image();
    String background_Image = "new_message";
    switch (image_index) {
        case 1:
            background_Image = "new_message.jpg";
            break;
        case 2:
            background_Image = "new_message2.jpg";
            break;
        case 3:
            background_Image = "new_message3.jpg";
            break;
        case 4:
            background_Image = "new_message4.jpg";
            break;
        case 5:
            background_Image = "new_message5.jpg";
            break;
        case 6:
            background_Image = "new_message6.jpg";
            break;
        case 7:
            background_Image = "new_message7.jpg";
            break;

        default:
            background_Image = "new_message.jpg";
    }
    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/" + background_Image)));
    Evenement.remplire_arry();
    try {
//     global_array.clear();
        ArrayList<Evenement_obj> ll1 = Evenement.all_event();

        global_array = ll1;

        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Nom Evenement", "Date Debut", "Date Fin", "Description"});

        for (int l = 0; l < ll1.size(); l++) {
            Evenement_obj rc = ll1.get(l);
            String[] nc = new String[]{rc.event_name, rc.Debut.toString(), rc.Fin.toString(), rc.event_description};
            dtm.addRow(nc);
        }
        jTable1.setModel(dtm);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Erreur !!!");
    }

    jDateChooser1.setVisible(false);
    if (operation == 0) {
        Supp.setVisible(false);
        Modi.setVisible(false);
    } else if (operation == 2) {
        Supp.setVisible(true);
        Modi.setVisible(false);
    } else if (operation == 1) {
        Supp.setVisible(false);
        Modi.setVisible(true);
    }


    // TODO add your handling code here:
}//GEN-LAST:event_formWindowOpened

private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
    String choix = jComboBox1.getSelectedItem().toString();
    //lors de la selection de Un jour
    if (choix.equals("Un jour")) {
        jDateChooser1.setVisible(true);

    } else {
        jDateChooser1.setVisible(false);
    }

    // Tous selectionner

    if (choix.equals("Tous")) {

        try {
//        global_array.clear();

            ArrayList<Evenement_obj> ll2 = Evenement.all_event();

            global_array = ll2;
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.setColumnIdentifiers(new String[]{"Nom Evenement", "Date Debut", "Date Fin", "Description"});

            for (int l = 0; l < ll2.size(); l++) {
                Evenement_obj rc = ll2.get(l);
                String[] nc = new String[]{rc.event_name, rc.Debut.toString(), rc.Fin.toString(), rc.event_description};
                dtm.addRow(nc);
            }
            jTable1.setModel(dtm);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Erreur !!!");
        }

    }
    if (choix.equals("Semaine prochaine")) {


        try {
// global_array.clear();
            ArrayList<Evenement_obj> ll3 = Evenement.all_event_afterWeek();

            global_array = ll3;

            DefaultTableModel dtm = new DefaultTableModel();
            dtm.setColumnIdentifiers(new String[]{"Nom Evenement", "Date Debut", "Date Fin", "Description"});




            for (int l = 0; l < ll3.size(); l++) {
                Evenement_obj rc = ll3.get(l);
                String[] nc = new String[]{rc.event_name, rc.Debut.toString(), rc.Fin.toString(), rc.event_description};

                dtm.addRow(nc);
            }
            jTable1.setModel(dtm);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Erreur !!!");
        }












    }
//    Tous
//Un jour
//
//Dernier Mois

}//GEN-LAST:event_jComboBox1ItemStateChanged

private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange

    if (jDateChooser1.getDate() != null) {

        try {
//             global_array.clear();
            ArrayList<Evenement_obj> ll4 = Evenement.all_event_at(jDateChooser1.getDate());
            global_array = ll4;

            DefaultTableModel dtm = new DefaultTableModel();
            dtm.setColumnIdentifiers(new String[]{"Nom Evenement", "Date Debut", "Date Fin", "Description"});




            for (int l = 0; l < ll4.size(); l++) {
                Evenement_obj rc = ll4.get(l);
                String[] nc = new String[]{rc.event_name, rc.Debut.toString(), rc.Fin.toString(), rc.event_description};

                dtm.addRow(nc);
            }
            jTable1.setModel(dtm);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Erreur !!!");
        }

    }

    // TODO add your handling code here:
}//GEN-LAST:event_jDateChooser1PropertyChange

private void SuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuppActionPerformed

    int index = jTable1.getSelectedRow();
    if (index == -1) {
        javax.swing.JOptionPane.showMessageDialog(null, "Aucune ligne selectionée !");
    } else {
         if (javax.swing.JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer l'evenement!!") == 0) {
        boolean a = Evenement.Delete_event(global_array.get(index));
//        if (a) {
//            System.out.println("mcha");
//        }


//mise a jours de la table
        try {

            ArrayList<Evenement_obj> ll = global_array;


            DefaultTableModel dtm = new DefaultTableModel();
            dtm.setColumnIdentifiers(new String[]{"Nom Evenement", "Date Debut", "Date Fin", "Description"});

            for (int l = 0; l < ll.size(); l++) {
                Evenement_obj rc = ll.get(l);
                String[] nc = new String[]{rc.event_name, rc.Debut.toString(), rc.Fin.toString(), rc.event_description};
                dtm.addRow(nc);
            }
            jTable1.setModel(dtm);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Erreur !!!");
        }}
    }

}//GEN-LAST:event_SuppActionPerformed

private void ModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModiActionPerformed
    int index = jTable1.getSelectedRow();
    if (index == -1) {
        javax.swing.JOptionPane.showMessageDialog(null, "Aucune ligne selectionée !");
    } else {
        Evenement_obj ev = global_array.get(index);
        Creat_Event cv = new Creat_Event();
        cv.nom.setText(ev.event_name);
        cv.desc.setText(ev.event_description);
        cv.Modification = true;
        cv.ev1 = ev;

        cv.setVisible(true);
    }
}//GEN-LAST:event_ModiActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    this.dispose();
    // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Consulter().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Modi;
    public javax.swing.JButton Supp;
    private javax.swing.JButton jButton1;
    public javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
