/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Creat_Event.java
 *
 * Created on Jun 3, 2012, 5:22:51 PM
 */
package snse;

import java.util.Date;

/**
 *
 * @author user
 */
public class Creat_Event extends javax.swing.JFrame {

    public boolean Modification = false;
    public Evenement_obj ev1 = null;

    /** Creates new form Creat_Event */
    public Creat_Event() {
        initComponents();
        this.setLocation(265, 51);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        date_fin = new com.toedter.calendar.JDateChooser();
        date_debut = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        h1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        mi1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        h2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        mi2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 630));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nom d'Evenement");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 140, 120, 17);
        getContentPane().add(nom);
        nom.setBounds(160, 130, 280, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date Debut");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 200, 90, 17);

        date_fin.setDateFormatString("MM/d/yyyy");
        getContentPane().add(date_fin);
        date_fin.setBounds(160, 260, 130, 30);

        date_debut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        date_debut.setDateFormatString("MM/d/yyyy");
        getContentPane().add(date_debut);
        date_debut.setBounds(160, 190, 130, 30);

        jButton1.setText("Creer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 543, 100, 30);

        h1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", " " }));
        getContentPane().add(h1);
        h1.setBounds(330, 190, 50, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("H");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 200, 9, 15);

        mi1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", " " }));
        getContentPane().add(mi1);
        mi1.setBounds(410, 190, 50, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Min");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(470, 200, 22, 15);

        h2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", " " }));
        getContentPane().add(h2);
        h2.setBounds(330, 260, 50, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Min");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(470, 270, 22, 15);

        mi2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", " " }));
        getContentPane().add(mi2);
        mi2.setBounds(410, 260, 50, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("H");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(390, 270, 9, 15);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date Fin");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 270, 60, 17);

        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 543, 90, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Creation d' Evenement ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 70, 220, 37);

        desc.setColumns(20);
        desc.setRows(5);
        jScrollPane1.setViewportView(desc);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 340, 380, 170);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Description");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 360, 80, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/new_message.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-10, 0, 700, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    boolean flag = true;

    Date cur = new Date();
    Date debut = date_debut.getDate();
    Date fin = date_fin.getDate();
    if (nom.getText() == null) {
        javax.swing.JOptionPane.showMessageDialog(null, "Nom Evenement obligatoire!!");
        flag = false;
    } else if (debut == null) {
        javax.swing.JOptionPane.showMessageDialog(null, "Date Debut vide!!");
        flag = false;
    } else if (fin == null) {
        javax.swing.JOptionPane.showMessageDialog(null, "Date Fin vide!!");
        flag = false;
    }
    if (flag) {


        int a = Integer.parseInt(h1.getSelectedItem().toString());

        debut.setHours(a);
        debut.setMinutes(Integer.parseInt(mi1.getSelectedItem().toString()));

        a = Integer.parseInt(h2.getSelectedItem().toString());

        fin.setHours(a);
        fin.setMinutes(Integer.parseInt(mi2.getSelectedItem().toString()));
        if (debut.before(fin) && cur.before(debut)) {
            Evenement_obj ev = new Evenement_obj();
            ev.Debut = debut;
            ev.Fin = fin;
            ev.event_description = desc.getText();
            ev.event_name = nom.getText();
            if (ev.event_description == null || ev.event_description.equals("")) {
                ev.event_description = "Aucun description";
            }
            if (jButton1.getText().equals("Sauvegarder")) {
                Evenement.Update_event(ev1, ev);
                javax.swing.JOptionPane.showMessageDialog(null, "Evenement Modifier !");

            } else {
                Evenement.Add_event(ev);
                javax.swing.JOptionPane.showMessageDialog(null, "Evenement Cree !");

            }
            this.dispose();
        } else {
            if (!cur.before(debut)) {
                javax.swing.JOptionPane.showMessageDialog(null, "Date De Debut evenement non valide !");
            } else if (!debut.before(fin)) {
                javax.swing.JOptionPane.showMessageDialog(null, "Date De fin evenement non valide !");
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Date Debu et fin d'Evenement non valide !");
            }

        }
    }

}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    if (Modification) {
        jButton1.setText("Sauvegarder");
    }
    int image_index = 0;
    image_index = Enregitrer.Dser_background_image();
    String background_Image = "new_message";
    switch (image_index) {
        case 1:
            background_Image = "new_message.jpg";
            break;
        case 2:
            background_Image = "new_message2.jpg";
            break;
        case 3:
            background_Image = "new_message3.jpg";
            break;
        case 4:
            background_Image = "new_message4.jpg";
            break;
        case 5:
            background_Image = "new_message5.jpg";
            break;
        case 6:
            background_Image = "new_message6.jpg";
            break;
        case 7:
            background_Image = "new_message7.jpg";
            break;

        default:
            background_Image = "new_message.jpg";
    }
    jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/" + background_Image)));

}//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creat_Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creat_Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creat_Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creat_Event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Creat_Event().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.toedter.calendar.JDateChooser date_debut;
    public com.toedter.calendar.JDateChooser date_fin;
    public javax.swing.JTextArea desc;
    public javax.swing.JComboBox h1;
    public javax.swing.JComboBox h2;
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox mi1;
    public javax.swing.JComboBox mi2;
    public javax.swing.JTextField nom;
    // End of variables declaration//GEN-END:variables
}
