/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Evenement_Detaille.java
 *
 * Created on Jun 4, 2012, 9:40:35 PM
 */
package snse;

/**
 *
 * @author user
 */
public class Evenement_Detaille extends javax.swing.JFrame {

    /** Creates new form Evenement_Detaille */
    public Evenement_Detaille() {
        initComponents();
        this.setLocation(290, 51);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fin = new javax.swing.JLabel();
        debut = new javax.swing.JLabel();
        Nom_event2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descr = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(590, 590));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nom d'Evenement");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 100, 120, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date Debut");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 160, 90, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date Fin");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 210, 60, 17);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Description");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 300, 80, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Consultation d'Evenement ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 30, 220, 37);

        fin.setFont(new java.awt.Font("Times New Roman", 2, 14));
        fin.setForeground(new java.awt.Color(255, 255, 255));
        fin.setText("Vous avez un nv message");
        fin.setName(""); // NOI18N
        getContentPane().add(fin);
        fin.setBounds(160, 210, 300, 30);

        debut.setFont(new java.awt.Font("Times New Roman", 2, 14));
        debut.setForeground(new java.awt.Color(255, 255, 255));
        debut.setText("Vous avez un nv message");
        debut.setName(""); // NOI18N
        getContentPane().add(debut);
        debut.setBounds(160, 150, 300, 30);

        Nom_event2.setFont(new java.awt.Font("Times New Roman", 2, 14));
        Nom_event2.setForeground(new java.awt.Color(255, 255, 255));
        Nom_event2.setText("Vous avez un nv message");
        Nom_event2.setName(""); // NOI18N
        getContentPane().add(Nom_event2);
        Nom_event2.setBounds(160, 100, 300, 30);

        descr.setColumns(20);
        descr.setRows(5);
        jScrollPane1.setViewportView(descr);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 250, 362, 202);

        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 473, 80, 30);

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 473, 80, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/new_message.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 580, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.dispose();
    // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.dispose();
    // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened


    int image_index = 0;
    image_index = Enregitrer.Dser_background_image();
    String background_Image = "new_message";
    switch (image_index) {
        case 1:
            background_Image = "new_message.jpg";
            break;
        case 2:
            background_Image = "new_message2.jpg";
            break;
        case 3:
            background_Image = "new_message3.jpg";
            break;
        case 4:
            background_Image = "new_message4.jpg";
            break;
        case 5:
            background_Image = "new_message5.jpg";
            break;
        case 6:
            background_Image = "new_message6.jpg";
            break;
        case 7:
            background_Image = "new_message7.jpg";
            break;

        default:
            background_Image = "new_message.jpg";
    }
    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/" + background_Image)));

    // TODO add your handling code here:
}//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evenement_Detaille.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evenement_Detaille.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evenement_Detaille.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evenement_Detaille.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Evenement_Detaille().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Nom_event2;
    public javax.swing.JLabel debut;
    public javax.swing.JTextArea descr;
    public javax.swing.JLabel fin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
