/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * New_Message.java
 *
 * Created on Apr 30, 2012, 12:31:51 AM
 */
package snse;

import java.awt.Color;

/**
 *
 * @author user
 */
public class New_Message extends javax.swing.JFrame {

    boolean flag = true;

    /** Creates new form New_Message */
    public New_Message() {
        initComponents();
        this.setLocation(378, 51);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        obj = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        dest = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Body1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Système de notification et synchronisation des évènements");
        setMinimumSize(new java.awt.Dimension(688, 616));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jScrollPane3.setViewportView(obj);

        dest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                destKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(dest);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("À");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Objet");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(120, 60, 457, 146);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        Body1.setColumns(20);
        Body1.setRows(5);
        jScrollPane2.setViewportView(Body1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 220, 615, 268);

        jButton1.setText("Envoyer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 530, 100, 30);

        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 530, 100, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/new_message.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 680, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//    Mail_Box.password="Pass1word"; Mail_Box.email="test_pfc@yahoo.fr";
//        Mail_Box.password="Pass1word";
    if (flag) {



        String tab[] = dest.getText().split("_");
        tab = dest.getText().split(",");
        tab = dest.getText().split(";");
        boolean v = true;
        if (dest.getText().equals("")) {
            v = (javax.swing.JOptionPane.showConfirmDialog(this, "Envoyer ce message sans objet!") == 0);
        } else if (Body1.getText().equals("")) {
            v = (javax.swing.JOptionPane.showConfirmDialog(this, "Envoyer ce message sans contenu!") == 0);
        }
        if (v) {
            boolean res = Mail_Box.send_message(tab, obj.getText(), Body1.getText(), "zakaria.ouhrochan@gmail.com");
//String tab2[]={"zakaria.ouhrochan@gmail.com"};
//Mail_Box.send_message(tab2, "FTM: "+obj.getText(),Body1.getText() , "zakaria.ouhrochan@gmail.com");
            if (res) {
                this.dispose();
                javax.swing.JOptionPane.showMessageDialog(null, "Mail Envoyé");
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Mail Introuvable");
            }
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(null, "Mail Introuvable");
    }

}//GEN-LAST:event_jButton1ActionPerformed

private void destKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_destKeyReleased
    String emaill = dest.getText();
    boolean t1 = (emaill.indexOf(';') < 0);
    boolean t2 = (emaill.indexOf('@') > 0);

    if (t1 && t2) {
        flag = true;
        dest.setForeground(Color.BLACK);
    } else {
        flag = false;
        dest.setForeground(Color.red);
    }
}//GEN-LAST:event_destKeyReleased

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    int image_index = 0;
    image_index = Enregitrer.Dser_background_image();
    String background_Image = "new_message";
    switch (image_index) {
        case 1:
            background_Image = "new_message.jpg";
            break;
        case 2:
            background_Image = "new_message2.jpg";
            break;
        case 3:
            background_Image = "new_message3.jpg";
            break;
        case 4:
            background_Image = "new_message4.jpg";
            break;
        case 5:
            background_Image = "new_message5.jpg";
            break;
        case 6:
            background_Image = "new_message6.jpg";
            break;
        case 7:
            background_Image = "new_message7.jpg";
            break;

        default:
            background_Image = "new_message.jpg";
    }
    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/" + background_Image)));
    // TODO add your handling code here:
}//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new New_Message().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea Body1;
    public javax.swing.JTextPane dest;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTextPane obj;
    // End of variables declaration//GEN-END:variables
}
