/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Notification_event.java
 *
 * Created on Jun 4, 2012, 4:54:20 PM
 */
package snse;

import java.awt.*;

/**
 *
 * @author user
 */
public class Notification_event extends javax.swing.JFrame {

    public int notipos;
    public Evenement_obj m;

    /** Creates new form Notification_event */
    public Notification_event(int noti) {
        this.setUndecorated(true);
        initComponents();
        Dimension scrSize = Toolkit.getDefaultToolkit().getScreenSize();// size of the screen
        Insets toolHeight = Toolkit.getDefaultToolkit().getScreenInsets(this.getGraphicsConfiguration());// height of the task bar
        notipos = noti;
        this.setLocation(scrSize.width - this.getWidth(), scrSize.height - toolHeight.bottom - this.getHeight() - notipos);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Debut = new javax.swing.JLabel();
        Fin = new javax.swing.JLabel();
        Nom_event = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(490, 350));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(419, 0, 50, 23);

        jButton2.setText("Plus de Detaille");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 280, 130, 23);

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(360, 280, 80, 23);

        jButton4.setText("Rappeler Moi");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(220, 280, 120, 23);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vous avez un nouveau Evenement");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 50, 290, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Evenement");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 140, 80, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date Fin:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 210, 100, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/e-mail-icon-294x30.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 21, 96, 100);

        Debut.setFont(new java.awt.Font("Times New Roman", 2, 14));
        Debut.setForeground(new java.awt.Color(255, 255, 255));
        Debut.setText("Vous avez un nv message");
        Debut.setName(""); // NOI18N
        getContentPane().add(Debut);
        Debut.setBounds(160, 170, 280, 30);

        Fin.setFont(new java.awt.Font("Times New Roman", 2, 14));
        Fin.setForeground(new java.awt.Color(255, 255, 255));
        Fin.setText("Vous avez un nv message");
        Fin.setName(""); // NOI18N
        getContentPane().add(Fin);
        Fin.setBounds(160, 200, 280, 30);

        Nom_event.setFont(new java.awt.Font("Times New Roman", 2, 14));
        Nom_event.setForeground(new java.awt.Color(255, 255, 255));
        Nom_event.setText("Vous avez un nv message");
        Nom_event.setName(""); // NOI18N
        getContentPane().add(Nom_event);
        Nom_event.setBounds(160, 140, 300, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date Debut:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 180, 100, 17);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/arrnotif.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 494, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    Evenement.Delete_event(m);
    this.dispose();
}//GEN-LAST:event_jButton3ActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    int image_index = 0;
    image_index = Enregitrer.Dser_background_image();
    String background_Image = "arrnotif";
    switch (image_index) {
        case 1:
            background_Image = "arrnotif.jpg";
            break;
        case 2:
            background_Image = "arrnotif2.jpg";
            break;
        case 3:
            background_Image = "arrnotif3.jpg";
            break;
        case 4:
            background_Image = "arrnotif4.jpg";
            break;
        case 5:
            background_Image = "arrnotif5.jpg";
            break;
        case 6:
            background_Image = "arrnotif6.jpg";
            break;
        case 7:
            background_Image = "arrnotif7.jpg";
            break;

        default:
            background_Image = "arrnotif.jpg";
    }
    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/" + background_Image)));

    // TODO add your handling code here:
}//GEN-LAST:event_formWindowOpened

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.dispose();// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    Evenement_Detaille evD = new Evenement_Detaille();
    evD.Nom_event2.setText(m.event_name);
    evD.debut.setText(m.Debut.toString());
    evD.fin.setText(m.Fin.toString());
    evD.descr.setText(m.event_description);
    Evenement.Delete_event(m);
    evD.setVisible(true);

    this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    this.dispose();
}//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notification_event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notification_event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notification_event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notification_event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            int a = 0;

            public void run() {
                new Notification_event(a).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Debut;
    public javax.swing.JLabel Fin;
    public javax.swing.JLabel Nom_event;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
